secret: openIM123
rpcRegisterName:
  user: user
  friend: friend
  msg: msg
  push: push
  messageGateway: messageGateway
  group: group
  auth: auth
  conversation: conversation
  third: third

imAdminUserID: [ imAdmin ]

# 0: No kick, but limit max number per platform (DefalutNotKick)
multiLogin:
  policy: 0
  maxNumOneEnd: 30